### ISSUE TITLE
Connecting to compute instance on SSH endpoint error - password required!

### ISSUE THREAD

**Issue by nguyenhung1121990** [matteote/azureml_shutdown_idle_compute_instances#1]
Hi Matteote,

Thanks for great script, that helps us much in understanding how to do further on that.  

I am doing the same steps as provided and looks that able to connect Azure ML workspace, however coming to step "Connecting to compute instance ... on SSH endpoint...", the ssh password is required while I am not setting it during first Compute Instance initiation.

Can you please advise? Or do we have alternate solution that using Service Principle instead, is that make sense?

Thanks in advance.
Hung.

**Comment by matteote** [comment]
Let's check the SSH key prerequisite first.
The script expects to use an SSH keypair, instead of a password.
It must be the default key of the user that runs the script (there is no option to override it).
The key is often created with `ssh-keygen`, but it's ultimately up to you to decide how to provision it.
The public key (typically from `~/.ssh/id_rsa.pub`) must be used when provisioning the Azure ML compute instance.

To test if the key is properly set up, you can manually ssh into the machine; it should succeed without prompting any password.
The command is something like this:
`ssh azureuser@10.137.131.133`
You should check the IP address of the compute instance from the Azure ML workspace.

Please check the above; let me know if the manual test works and the script keeps failing.
If the manual test fails (asks you a password), there may be an issue with the configuration of the key, or with the provisioning of the compute instance.

**Comment by rndazurescript** [comment]
When creating the compute instance, you have to enable the SSH access and specify the public key that you have on your computer (e.g. the content of `~/.ssh/id_rsa.pub`) as shown in :
![image](https://user-images.githubusercontent.com/61463978/169233503-f4a83196-0e0b-42b9-9022-4e1fbeefcffc.png)

**Comment by nguyenhung1121990** [comment]
I understood. Also tested and that's working.

I am concerning if any option to "restrict" if the "Enable ssh access" use only these unique SSH Public key  provided Administrator (to avoid end-users created their Compute themselves)? can Azure Policy help?

**Comment by matteote** [comment]
Yes, you can use a policy like the following, that denies the creation of the compute instance if the key does not match.
I will mark the issue as closed.

```json
{
    "mode": "All",
    "parameters": {
        "public-key": {
            "type": "String",
            "metadata": {
                "displayName": "SSH public key",
                "description": "SSH public key to enforce"
            }
        }
    },
    "policyRule": {
        "if": {
            "allOf": [
                {
                    "field": "type",
                    "equals": "Microsoft.MachineLearningServices/workspaces/computes"
                },
                {
                    "field": "Microsoft.MachineLearningServices/workspaces/computes/computeType",
                    "equals": "ComputeInstance"
                },
                {
                    "field": "Microsoft.MachineLearningServices/workspaces/computes/sshSettings.adminPublicKey",
                    "notEquals": "[parameters('public-key')]"
                }
            ]
        },
        "then": {
            "effect": "deny"
        }
    }
}
```
